# TODO: UMN AnyConnect / Cisco Secure Client: https://it.umn.edu/services-technologies/virtual-private-network-vpn
# TODO: Cricut Design Space: https://design.cricut.com/

tap "bsoyka/extras"
tap "nrlquaker/createzap"

brew "age"           # encryption
brew "awscli"        # Amazon Web Services CLI
brew "bat"           # file viewer (cat alternative)
brew "chezmoi"       # dotfile manager
brew "cloc"          # count lines of code
brew "direnv"        # environment variable automation
brew "eza"           # file structure viewer (ls alternative)
brew "fd"            # find alternative
brew "fish"          # shell
brew "fzf"           # fuzzy finder
brew "gcc"           # compiler infrastructure
brew "gh"            # GitHub interface
brew "git"           # version control
brew "glow"          # Markdown previewer
brew "gnupg"         # OpenPGP implementation
brew "googletest"    # Google Test framework
brew "httpie"        # curl alternative
brew "hyperfine"     # benchmarking tool
brew "imagemagick"   # image processing
brew "jq"            # JSON query tool
brew "lazygit"       # visual git interface
brew "llvm"          # compiler infrastructure
brew "lsd"           # file structure viewer (ls alternative)
brew "make"          # compilation recipe tool
brew "mas"           # Mac apps in Brewfile
brew "mise"          # tool version manager
brew "mole"          # storage cleaning tool
brew "rclone"        # cloud storage sync tool
brew "ripgrep"       # search tool (grep alternative)
brew "tailscale"     # WireGuard platform
brew "thefuck"       # command fixer
brew "tlrc"          # tldr search
brew "topgrade"      # mass upgrade tool
brew "tree"          # directory tree viewer
brew "uv"            # Python package and project manager
brew "wget"          # internet file retriever
brew "xan"           # CSV tool
brew "xxh"           # send config over SSH
brew "zoxide"        # navigation shortcut tool

cask "1password"
cask "1password-cli"
cask "adobe-creative-cloud"
cask "affinity"
cask "altos" # from bsoyka/extras
cask "appcleaner"
cask "audacity"
cask "bambu-studio"
cask "betterdisplay"
cask "brave-browser"
cask "cardhop"
cask "cloudmounter"
cask "devtoys"
cask "discord"
cask "ghostty"
cask "github"
cask "gnucash"
cask "gpg-suite"
cask "grammarly-desktop"
cask "home-assistant"
cask "huggle" # from bsoyka/extras
cask "keybase"
cask "label-live"
cask "launchcontrol"
cask "libreoffice"
cask "mactex"
cask "obs"
cask "obsidian"
cask "openrocket"
cask "orbstack"
cask "parallels"
cask "pingid"
cask "raycast"
cask "setapp"
cask "shottr"
cask "signal"
cask "skim"
cask "slack"
cask "spotify"
cask "stats"
cask "tailscale-app"
cask "topaz-photo"
cask "windows-app"
cask "zed"
cask "zoom"
cask "zotero"

cask "font-fira-code-nerd-font"
cask "font-ibm-plex-sans"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"

mas "1Password for Safari", id: 1569813296
mas "Amphetamine", id: 937984704
mas "Crouton", id: 1461650987
mas "Deliveries", id: 290986013
mas "Endel", id: 1346247457
mas "Flighty", id: 1358823008
mas "Goodnotes", id: 1444383602
mas "HP Smart", id: 1474276998
mas "Notability", id: 360593530
mas "TestFlight", id: 899247664
mas "Things", id: 904280696
