[[watch]]
path = "~/Downloads"
recursive = false

[[watch]]
path = "~/switchboard/uploaded"
recursive = false

[[rule]]
name = "Clean Old Files"
enabled = true

[rule.condition]
age_days_greater_than = 3

[rule.action]
type = "trash"
